"""initial

Revision ID: 545008c36577
Revises: 
Create Date: 2026-05-13 20:57:35.454874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '545008c36577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Text().with_variant(sa.Text(), 'mysql').with_variant(sa.Text(), 'postgresql').with_variant(sa.BigInteger(), 'sqlite'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('signupToken', sa.Text(), nullable=False),
    sa.Column('modifiedBy', sa.Text().with_variant(sa.Text(), 'mysql').with_variant(sa.Text(), 'postgresql').with_variant(sa.BigInteger(), 'sqlite'), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('teamId', sa.Text(), nullable=False),
    sa.Column('channelId', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('showDescription', sa.Boolean(), nullable=False),
    sa.Column('isTemplate', sa.Boolean(), nullable=False),
    sa.Column('templateVersion', sa.Integer(), nullable=False),
    sa.Column('minimumRole', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('userID', sa.Text(), nullable=False),
    sa.Column('teamID', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('expiresAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('parentId', sa.Text(), nullable=True),
    sa.Column('createdBy', sa.Text(), nullable=False),
    sa.Column('modifiedBy', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('fields', sqlite.JSON(), nullable=False),
    sa.Column('schema', sa.Integer(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modifiedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parentId'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_history',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('teamId', sa.Text(), nullable=False),
    sa.Column('channelId', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('showDescription', sa.Boolean(), nullable=False),
    sa.Column('isTemplate', sa.Boolean(), nullable=False),
    sa.Column('templateVersion', sa.Integer(), nullable=False),
    sa.Column('minimumRole', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_limits',
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('cards', sa.Integer(), nullable=False),
    sa.Column('usedCards', sa.Integer(), nullable=False),
    sa.Column('cardLimitTimestamp', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('boardId')
    )
    op.create_table('board_members',
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('minimumRole', sa.Text(), nullable=False),
    sa.Column('schemeAdmin', sa.Boolean(), nullable=False),
    sa.Column('schemeEditor', sa.Boolean(), nullable=False),
    sa.Column('schemeCommenter', sa.Boolean(), nullable=False),
    sa.Column('schemeViewer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('boardId', 'userId')
    )
    op.create_table('category_boards',
    sa.Column('categoryId', sa.Text(), nullable=False),
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('categoryId', 'boardId')
    )
    op.create_table('file_infos',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mimeType', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sharings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_history',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('blockId', sa.Text(), nullable=False),
    sa.Column('boardId', sa.Text(), nullable=False),
    sa.Column('parentId', sa.Text(), nullable=False),
    sa.Column('createdBy', sa.Text(), nullable=False),
    sa.Column('modifiedBy', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('fields', sqlite.JSON(), nullable=False),
    sa.Column('schema', sa.Integer(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.Column('deleteAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['blockId'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('blockId', sa.Text(), nullable=False),
    sa.Column('subscriberId', sa.Text(), nullable=False),
    sa.Column('subscriberType', sa.Text(), nullable=False),
    sa.Column('createAt', sa.BigInteger(), nullable=False),
    sa.Column('notifyAt', sa.BigInteger(), nullable=False),
    sa.Column('updateAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['blockId'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('blockId', 'subscriberId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('block_history')
    op.drop_table('sharings')
    op.drop_table('file_infos')
    op.drop_table('category_boards')
    op.drop_table('board_members')
    op.drop_table('board_limits')
    op.drop_table('board_history')
    op.drop_table('blocks')
    op.drop_table('sessions')
    op.drop_table('categories')
    op.drop_table('boards')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
