"""001_initial_schema

Revision ID: 7ad2a3c9fd3a
Revises: 
Create Date: 2026-05-24 18:29:32.419244
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ad2a3c9fd3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_hints',
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('modify_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('modify_at >= 0', name='ck_notification_hints_modify_at_non_negative'),
    sa.PrimaryKeyConstraint('block_type', 'block_id')
    )
    op.create_index('ix_notification_hints_modify_at', 'notification_hints', ['modify_at'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("type IN ('O', 'P')", name='ck_teams_type_valid'),
    sa.CheckConstraint('delete_at >= 0', name='ck_teams_delete_at_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_delete_at', 'teams', ['delete_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('delete_at >= 0', name='ck_users_delete_at_non_negative'),
    sa.CheckConstraint('length(trim(email)) > 0', name='ck_users_email_not_blank'),
    sa.CheckConstraint('length(trim(username)) > 0', name='ck_users_username_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_delete_at', 'users', ['delete_at'], unique=False)
    op.create_index('ix_users_email_delete_at', 'users', ['email', 'delete_at'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('modified_by', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('minimum_role', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('show_description', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('card_properties', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("minimum_role IN ('', 'viewer', 'commenter', 'editor', 'admin')", name='ck_boards_minimum_role_valid'),
    sa.CheckConstraint("type IN ('O', 'P')", name='ck_boards_type_valid'),
    sa.CheckConstraint('delete_at >= 0', name='ck_boards_delete_at_non_negative'),
    sa.CheckConstraint('template_version >= 0', name='ck_boards_template_version_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_boards_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name='fk_boards_modified_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_boards_team', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boards_created_by', 'boards', ['created_by'], unique=False)
    op.create_index('ix_boards_team_id_delete_at', 'boards', ['team_id', 'delete_at'], unique=False)
    op.create_index('ix_boards_type_delete_at', 'boards', ['type', 'delete_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("type IN ('system', 'custom')", name='ck_categories_type_valid'),
    sa.CheckConstraint('delete_at >= 0', name='ck_categories_delete_at_non_negative'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_categories_team', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_categories_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_user_team_delete_at', 'categories', ['user_id', 'team_id', 'delete_at'], unique=False)
    op.create_table('preferences',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.CheckConstraint('length(trim(category)) > 0', name='ck_preferences_category_not_blank'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_preferences_name_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_preferences_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category', 'name')
    )
    op.create_index('ix_preferences_user_category', 'preferences', ['user_id', 'category'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('last_active_time', sa.BigInteger(), nullable=True),
    sa.Column('expire_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('expire_at >= create_at', name='ck_sessions_expire_at_gte_create_at'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sessions_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_sessions_expire_at', 'sessions', ['expire_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('subscriber_type', sa.Text(), nullable=False),
    sa.Column('subscriber_id', sa.Text(), nullable=False),
    sa.Column('notify_frequency', sa.Text(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('publish_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("subscriber_type = 'user'", name='ck_subscriptions_subscriber_type_user'),
    sa.CheckConstraint('publish_at >= 0', name='ck_subscriptions_publish_at_non_negative'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], name='fk_subscriptions_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_type', 'block_id', 'subscriber_type', 'subscriber_id')
    )
    op.create_index('ix_subscriptions_block', 'subscriptions', ['block_id', 'block_type'], unique=False)
    op.create_index('ix_subscriptions_subscriber_id', 'subscriptions', ['subscriber_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('scheme_guest', sa.Boolean(), nullable=False),
    sa.Column('scheme_user', sa.Boolean(), nullable=False),
    sa.Column('scheme_admin', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('NOT (scheme_guest = TRUE AND scheme_admin = TRUE)', name='ck_team_members_guest_admin_exclusive'),
    sa.CheckConstraint('NOT (scheme_guest = TRUE AND scheme_user = TRUE)', name='ck_team_members_guest_user_exclusive'),
    sa.CheckConstraint('delete_at >= 0', name='ck_team_members_delete_at_non_negative'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_team_members_team', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_team_members_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index('ix_team_members_user_id_delete_at', 'team_members', ['user_id', 'delete_at'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('root_id', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('modified_by', sa.Text(), nullable=True),
    sa.Column('schema', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.Text(), nullable=False),
    sa.CheckConstraint('delete_at >= 0', name='ck_blocks_delete_at_non_negative'),
    sa.CheckConstraint('schema >= 1', name='ck_blocks_schema_min'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='fk_blocks_board', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_blocks_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name='fk_blocks_modified_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['blocks.id'], name='fk_blocks_parent', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_id'], ['blocks.id'], name='fk_blocks_root', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blocks_board_id_delete_at', 'blocks', ['board_id', 'delete_at'], unique=False)
    op.create_index('ix_blocks_parent_id', 'blocks', ['parent_id'], unique=False)
    op.create_index('ix_blocks_root_id', 'blocks', ['root_id'], unique=False)
    op.create_index('ix_blocks_type_board_delete_at', 'blocks', ['type', 'board_id', 'delete_at'], unique=False)
    op.create_table('blocks_history',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('root_id', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('modified_by', sa.Text(), nullable=True),
    sa.Column('schema', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.Text(), nullable=False),
    sa.Column('insert_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('delete_at > 0', name='ck_blocks_history_delete_at_positive'),
    sa.CheckConstraint('insert_at >= create_at', name='ck_blocks_history_insert_at_gte_create_at'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='fk_blocks_history_board', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_blocks_history_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name='fk_blocks_history_modified_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'insert_at')
    )
    op.create_index('ix_blocks_history_board_id_insert_at', 'blocks_history', ['board_id', 'insert_at'], unique=False)
    op.create_index('ix_blocks_history_delete_at', 'blocks_history', ['delete_at'], unique=False)
    op.create_table('board_members',
    sa.Column('board_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('scheme_admin', sa.Boolean(), nullable=False),
    sa.Column('scheme_editor', sa.Boolean(), nullable=False),
    sa.Column('scheme_commenter', sa.Boolean(), nullable=False),
    sa.Column('scheme_viewer', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('\n            (CASE WHEN scheme_admin THEN 1 ELSE 0 END) +\n            (CASE WHEN scheme_editor THEN 1 ELSE 0 END) +\n            (CASE WHEN scheme_commenter THEN 1 ELSE 0 END) +\n            (CASE WHEN scheme_viewer THEN 1 ELSE 0 END) <= 1\n            ', name='ck_board_members_single_scheme'),
    sa.CheckConstraint('delete_at >= 0', name='ck_board_members_delete_at_non_negative'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='fk_board_members_board', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_board_members_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'user_id')
    )
    op.create_index('ix_board_members_user_id_delete_at', 'board_members', ['user_id', 'delete_at'], unique=False)
    op.create_table('category_boards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Text(), nullable=False),
    sa.Column('board_id', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('hide', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('delete_at >= 0', name='ck_category_boards_delete_at_non_negative'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='fk_category_boards_board', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_category_boards_category', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_category_boards_team', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_category_boards_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'board_id', 'user_id', name='uq_category_boards_unique')
    )
    op.create_index('ix_category_boards_board_id_delete_at', 'category_boards', ['board_id', 'delete_at'], unique=False)
    op.create_index('ix_category_boards_category_sort', 'category_boards', ['category_id', 'sort_order'], unique=False)
    op.create_table('file_info',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('board_id', sa.Text(), nullable=True),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('extension', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('has_preview_image', sa.Boolean(), nullable=False),
    sa.CheckConstraint('delete_at >= 0', name='ck_file_info_delete_at_non_negative'),
    sa.CheckConstraint('size IS NULL OR size >= 0', name='ck_file_info_size_non_negative'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='fk_file_info_board', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_file_info_creator', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_info_board_id_delete_at', 'file_info', ['board_id', 'delete_at'], unique=False)
    op.create_index('ix_file_info_creator_id', 'file_info', ['creator_id'], unique=False)
    op.create_table('sharing',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('modified_by', sa.Text(), nullable=True),
    sa.Column('update_at', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['boards.id'], name='fk_sharing_board', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name='fk_sharing_modified_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_sharing_enabled', 'sharing', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sharing_enabled', table_name='sharing')
    op.drop_table('sharing')
    op.drop_index('ix_file_info_creator_id', table_name='file_info')
    op.drop_index('ix_file_info_board_id_delete_at', table_name='file_info')
    op.drop_table('file_info')
    op.drop_index('ix_category_boards_category_sort', table_name='category_boards')
    op.drop_index('ix_category_boards_board_id_delete_at', table_name='category_boards')
    op.drop_table('category_boards')
    op.drop_index('ix_board_members_user_id_delete_at', table_name='board_members')
    op.drop_table('board_members')
    op.drop_index('ix_blocks_history_delete_at', table_name='blocks_history')
    op.drop_index('ix_blocks_history_board_id_insert_at', table_name='blocks_history')
    op.drop_table('blocks_history')
    op.drop_index('ix_blocks_type_board_delete_at', table_name='blocks')
    op.drop_index('ix_blocks_root_id', table_name='blocks')
    op.drop_index('ix_blocks_parent_id', table_name='blocks')
    op.drop_index('ix_blocks_board_id_delete_at', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index('ix_team_members_user_id_delete_at', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('ix_subscriptions_subscriber_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_block', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expire_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_preferences_user_category', table_name='preferences')
    op.drop_table('preferences')
    op.drop_index('ix_categories_user_team_delete_at', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_boards_type_delete_at', table_name='boards')
    op.drop_index('ix_boards_team_id_delete_at', table_name='boards')
    op.drop_index('ix_boards_created_by', table_name='boards')
    op.drop_table('boards')
    op.drop_index('ix_users_email_delete_at', table_name='users')
    op.drop_index('ix_users_delete_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_teams_delete_at', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_notification_hints_modify_at', table_name='notification_hints')
    op.drop_table('notification_hints')
    # ### end Alembic commands ###
